#!/usr/bin/env python
# PYTHON_ARGCOMPLETE_OK
"""Legacy entry point for ansible-test. The preferred version is in the bin directory."""
from __future__ import (absolute_import, division, print_function)
__metaclass__ = type

import lib.cli

if __name__ == '__main__':
    lib.cli.main()
