# NOTE: `distlib` is untyped as of 10 Oct 2025.
# NOTE: This should be removed once types are upstream.
# Ref: https://github.com/pypa/distlib/pull/195

class Manifest:
    def __init__(self, base: str | None = ...) -> None: ...
    def process_directive(self, directive: str) -> None: ...
    def sorted(self, wantdirs: bool = ...) -> list[str]: ...
