#!/usr/bin/python

# (c) 2012, Michael DeHaan <michael.dehaan@gmail.com>
#
# This file is part of Ansible
#
# Ansible is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Ansible is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Ansible.  If not, see <http://www.gnu.org/licenses/>.

import base64

# this is magic, see lib/ansible/module_common.py
#<<INCLUDE_ANSIBLE_MODULE_COMMON>>

module = AnsibleModule(
    argument_spec = dict(
        src=(None,True),
    )
)
source = module.params['src']

if not os.path.exists(source):
    module.fail_json(msg="file not found: %s" % source)
if not os.access(source, os.R_OK):
    module.fail_json(msg="file is not readable: %s" % source)

data = base64.b64encode(file(source).read())

module.exit_json(content=data, encoding='base64')

