examples/hosts etc/ansible
docs/man/man1/*.1 usr/share/man/man1
debian/tmp/usr/bin/ansible-galaxy usr/bin
debian/tmp/usr/bin/ansible-vault usr/bin
debian/tmp/usr/bin/ansible-doc usr/bin
debian/tmp/usr/bin/ansible-console usr/bin
debian/tmp/usr/bin/ansible-connection usr/bin
debian/tmp/usr/bin/ansible-inventory usr/bin
debian/tmp/usr/bin/ansible-config usr/bin
debian/tmp/usr/bin/ansible-pull usr/bin
debian/tmp/usr/bin/ansible-playbook usr/bin
debian/tmp/usr/bin/ansible usr/bin
examples/ansible.cfg etc/ansible
debian/tmp/usr/lib/python2.7/dist-packages/ansible usr/lib/python2.7/dist-packages
debian/tmp/usr/lib/python2.7/dist-packages/ansible-*.egg-info
