releases:
  2.6.0:
    codename: Heartbreaker
    fragments:
    - v2.6.0_summary.yaml
    release_date: '2018-06-28'
  2.6.0a1:
    codename: Heartbreaker
    fragments:
    - ansible-managed-encoding.yaml
    - azure-lb-sku.yaml
    - base64_filter_encoding.yaml
    - command-support-argv.yaml
    - copy-files-default-follow.yaml
    - copy-no-chmod.yaml
    - copy-recursive-copy.yml
    - encoding-docs-plugin-parsing.yaml
    - file-disallow-src.yaml
    - file-nonexistent-link.yaml
    - file-nonexitent-link-recurse.yaml
    - file-succeed-if-already-absent.yaml
    - gem-custom-home.yaml
    - grafana-deprecation-warnings.yaml
    - includes.yaml
    - mode-preserve.yaml
    - pause-ctrl-c.yaml
    - postgresql_user-encrypted-fixes.yml
    - py36-spwd.yaml
    - template-filename-encoding.yaml
    - user-expires.yaml
    - v2.6.0a1_catchup.yaml
    - v2.6.0a1_summary.yaml
    - win_environment-do-not-delete-on-null.yaml
    - win_file-special-char-fix.yaml
    - win_get_url-ftp-support.yaml
    - win_module_utils_sid-conversion.yaml
    - win_template-dest-dir-fix.yaml
    - win_updates_typo_whitelist_fix.yaml
    - window_become-better-errors.yaml
    - windows-deprecation-removal.yaml
    - winrm-encoding-fix
    - winrm-get_correct_user.yaml
    - yaml-callback-unicode.yaml
    modules:
    - aci_l3out
    - avi_autoscalelaunchconfig
    - avi_l4policyset
    - avi_useraccount
    - aws_caller_facts
    - aws_inspector_target
    - aws_ses_identity_policy
    - aws_sgw_facts
    - azure_rm_aks
    - azure_rm_aks_facts
    - bigip_data_group
    - bigip_device_license
    - bigip_gtm_global
    - bigip_gtm_monitor_bigip
    - bigip_gtm_monitor_firepass
    - bigip_gtm_monitor_http
    - bigip_gtm_monitor_https
    - bigip_gtm_monitor_tcp
    - bigip_gtm_monitor_tcp_half_open
    - bigip_gtm_pool_member
    - bigip_gtm_virtual_server
    - bigip_log_destination
    - bigip_log_publisher
    - bigip_management_route
    - bigip_profile_dns
    - bigip_profile_tcp
    - bigip_profile_udp
    - bigip_service_policy
    - bigip_smtp
    - bigip_snmp_community
    - bigip_timer_policy
    - bigip_trunk
    - bigiq_application_fasthttp
    - bigiq_application_fastl4_tcp
    - bigiq_application_fastl4_udp
    - bigiq_application_http
    - bigiq_application_https_offload
    - bigiq_application_https_waf
    - bigiq_regkey_license_assignment
    - cnos_command
    - cnos_config
    - cs_role_permission
    - digital_ocean_account_facts
    - digital_ocean_certificate_facts
    - digital_ocean_domain_facts
    - digital_ocean_image_facts
    - digital_ocean_load_balancer_facts
    - digital_ocean_region_facts
    - digital_ocean_size_facts
    - digital_ocean_snapshot_facts
    - digital_ocean_tag_facts
    - digital_ocean_volume_facts
    - ec2_eip_facts
    - ec2_vpc_vpn_facts
    - exos_command
    - fortios_webfilter
    - gcp_compute_address
    - gcp_compute_backend_bucket
    - gcp_compute_backend_service
    - gcp_compute_health_check
    - gcp_compute_http_health_check
    - gcp_compute_https_health_check
    - gcp_compute_instance
    - gcp_compute_instance_template
    - gcp_compute_network
    - gcp_compute_route
    - gcp_compute_subnetwork
    - gcp_compute_target_http_proxy
    - gcp_compute_target_https_proxy
    - gcp_compute_target_tcp_proxy
    - gcp_container_cluster
    - gcp_container_node_pool
    - gcp_dns_resource_record_set
    - gcp_pubsub_subscription
    - gcp_pubsub_topic
    - gcp_storage_bucket
    - gcp_storage_bucket_access_control
    - gitlab_deploy_key
    - gitlab_hooks
    - k8s
    - ldap_passwd
    - memset_zone
    - meraki_network
    - meraki_organization
    - na_ontap_broadcast_domain
    - net_get
    - net_put
    - netconf_get
    - one_host
    - one_image
    - one_image_facts
    - one_vm
    - os_server_metadata
    - os_volume_snapshot
    - psexec
    - purefa_ds
    - purefa_facts
    - purefa_pgsnap
    - purefb_fs
    - purefb_snap
    - rds_instance_facts
    - rds_snapshot_facts
    - scaleway_compute
    - scaleway_sshkey
    - slxos_command
    - slxos_config
    - slxos_facts
    - slxos_interface
    - slxos_l2_interface
    - slxos_linkagg
    - spectrum_device
    - sysvinit
    - vmware_cluster_facts
    - vmware_datastore_cluster
    - vmware_datastore_maintenancemode
    - vmware_guest_disk_facts
    - vmware_guest_snapshot_facts
    - vmware_host_capability_facts
    - vmware_host_powerstate
    - vmware_local_user_facts
    - vmware_portgroup_facts
    - vmware_resource_pool_facts
    - vmware_tag
    - vmware_tag_facts
    - vmware_vswitch_facts
    - win_domain_computer
    - win_hostname
    - win_pester
    - yarn
    - zabbix_group_facts
    plugins:
      callback:
      - cgroup_memory_recap
      - grafana_annotations
      - sumologic
      connection:
      - httpapi
      inventory:
      - foreman
      - generator
      - nmap
      lookup:
      - onepassword
      - onepassword_raw
    release_date: '2018-05-21'
  2.6.0a2:
    codename: Heartbreaker
    fragments:
    - always_run_removal.yaml
    - aws_ses_identity_check_mode.yaml
    - powershell_use_set_tmpdir.yaml
    - selinux-check-mode.yaml
    - synchronize_remote_is_local.yaml
    - v2.6.0a2_catchup.yaml
    - v2.6.0a2_summary.yaml
    - win_updates-add-scheduled-tasks-back.yaml
    - winrm_kinit_error-fix.yaml
    - xenserver-facts-fix.yaml
    modules:
    - acme_account
    - aws_config_aggregation_authorization
    - aws_config_aggregator
    - aws_config_delivery_channel
    - aws_config_recorder
    - aws_config_rule
    - aws_glue_connection
    - aws_glue_job
    - azure_rm_resource
    - azure_rm_resource_facts
    - bigip_gtm_monitor_external
    - bigip_monitor_external
    - bigiq_utility_license
    - cloud_init_data_facts
    - elb_network_lb
    - flatpak
    - flatpak_remote
    - gcp_compute_disk
    - gcp_compute_firewall
    - gcp_compute_forwarding_rule
    - gcp_compute_global_address
    - gcp_compute_global_forwarding_rule
    - gcp_compute_image
    - gcp_compute_instance_group
    - gcp_compute_instance_group_manager
    - gcp_compute_ssl_certificate
    - gcp_compute_target_pool
    - gcp_compute_target_ssl_proxy
    - gcp_compute_url_map
    - gluster_peer
    - heroku_collaborator
    - memset_dns_reload
    - memset_zone_domain
    - memset_zone_record
    - meraki_admin
    - meraki_snmp
    - na_ontap_aggregate
    - na_ontap_broadcast_domain_ports
    - na_ontap_cifs
    - na_ontap_cifs_acl
    - na_ontap_cifs_server
    - na_ontap_cluster
    - na_ontap_cluster_ha
    - na_ontap_export_policy
    - na_ontap_export_policy_rule
    - na_ontap_igroup
    - na_ontap_interface
    - na_ontap_iscsi
    - na_ontap_job_schedule
    - na_ontap_license
    - na_ontap_lun
    - na_ontap_lun_map
    - na_ontap_net_ifgrp
    - na_ontap_net_port
    - na_ontap_net_routes
    - na_ontap_net_vlan
    - na_ontap_nfs
    - na_ontap_ntp
    - na_ontap_qtree
    - na_ontap_service_processor_network
    - na_ontap_snapshot
    - na_ontap_snmp
    - na_ontap_svm
    - na_ontap_ucadapter
    - na_ontap_user
    - na_ontap_user_role
    - na_ontap_volume
    - na_ontap_volume_clone
    - netconf_rpc
    - one_service
    - slxos_l3_interface
    - slxos_vlan
    plugins:
      inventory:
      - gcp_compute
    release_date: '2018-05-30'
  2.6.0rc1:
    codename: Heartbreaker
    fragments:
    - v2.6.0rc1_catchup.yaml
    - v2.6.0rc1_summary.yaml
    release_date: '2018-06-05'
  2.6.0rc2:
    codename: Heartbreaker
    fragments:
    - 41167_ansible_doc_regression.yaml
    - admin-users-default-change.yaml
    - aws_s3_async_fix.yaml
    - aws_s3_decryption_fix.yaml
    - aws_s3_fix_custom_endpoints.yaml
    - aws_s3_fix_exception_handling.yaml
    - ec2_ami_fix_block_device_mapping_volume_size_type.yaml
    - v2.6.0rc2_summary.yaml
    release_date: '2018-06-08'
  2.6.0rc3:
    codename: Heartbreaker
    fragments:
    - digital_ocean_block_storage_fix.yaml
    - gce-sort-fix.yaml
    - iosxr_config_route_policy_objects_fix.yaml
    - no_log_fix_for_connection_exceptions.yaml
    - reset_con_fix.yml
    - v2.6.0rc3_summary.yaml
    release_date: '2018-06-18'
  2.6.0rc4:
    codename: Heartbreaker
    fragments:
    - 41530-apt-mark-deb6.yaml
    - debug_fixes.yml
    - eos_vrf_failure-fix.yml
    - file_touch_diff.yaml
    - fix_config_required.yml
    - fix_yaml_inv_nulls.yml
    - missing_raise.yml
    - v2.6.0rc4_summary.yaml
    - vars_lk.yml
    - virtualbox_inventory.yaml
    - win_updates-async-fix.yml
    - winrm_kinit-remove-pass-log.yml
    release_date: '2018-06-25'
  2.6.0rc5:
    codename: Heartbreaker
    fragments:
    - fix_options.yml
    - fix_password_lookup_loading.yaml
    - group_by_localhost.yaml
    - lineinfile-insertbefore-bof-bugfix.yaml
    - v2.6.0rc5_summary.yaml
    - win_iis_webapppool-output-fix.yml
    release_date: '2018-06-26'
  2.6.1:
    codename: Heartbreaker
    fragments:
    - avoid_cwd_vars.yml
    - basic_booleans_backward_compat.yaml
    - file_touch_check_mode.yaml
    - inventory_manager_fix_required_options_override.yaml
    - junos_config_confirm_commit.yaml
    - nsupdate_fix_hmac-sha384.yaml
    - v2.6.1_summary.yaml
    - win_domain-dns-typo-fix.yml
    - win_group_membership-sid-bugfix.yml
    - wrcwd_ansible.cfg.yml
    release_date: '2018-07-05'
  2.6.2:
    codename: Heartbreaker
    fragments:
    - 40839-docker_container_init.yml
    - 42042-inventory_with_no_region.yaml
    - 42647-win_updates.yaml
    - clarify_error_message.yml
    - doc_fix.yml
    - docfix.yml
    - docker-default-ssl.yml
    - empty_gh_error.yaml
    - ensure_text_source.yaml
    - eos_l2_interface_fix.yaml
    - fix_fact_clean.yaml
    - fix_ios_vlan.yaml
    - fix_pagination_cloudfront_facts.yml
    - fix_sysvinit_typo.yml
    - fix_tls_mail.yaml
    - inventory_dir_ext_compare_fix.yaml
    - ios_l2_interface-fix.yml
    - junos_facts_fix.yaml
    - lineinfile-empty-regexp.yml
    - nxos_CI_failures_fix.yaml
    - nxos_cliconf.yaml
    - nxos_facts.yaml
    - nxos_module_utils_nxapi_get_capabilities.yaml
    - nxos_nxapi_default_http_behavior_fix.yaml
    - nxos_vxlan_vtep_vni_fix.yaml
    - openvswitch_db_make_key_optional.yaml
    - pause-stdout-redirection.yaml
    - pause-try-except-curses.yaml
    - preserve_delegate_nolog.yml
    - remote_tmp_de-escalated_user.yaml
    - sysvinit_bugxif.yml
    - user-freebsd-createhome-name-fix.yaml
    - user_freebsd_always_changed_bugfix.yaml
    - v2.6.2_summary.yaml
    - vmware_remove_vm_sceanrio.yaml
    - vultr-parameters-parsing.yaml
    - vyos_command_retry.yml
    - win_chocoalatey_install_tls12.yml
    - win_reboot-fixes.yml
    - win_security_policy-empty-value.yaml
    - win_unzip_share-discard-cmdlet-output.yaml
    - win_user-validate-fixes.yaml
    release_date: '2018-07-27'
  2.6.3:
    codename: Heartbreaker
    fragments:
    - 42786-sysvinit-fix-2-issues.yml
    - 42943_vmware_vmnic_fix.yaml
    - azure_nsg_deployment_lb.yaml
    - convert-valid-data-to-bytes-for-conversion.yaml
    - fix-selectors-error-condition.yaml
    - fix-swap-mount-module.yaml
    - fix-world-readable-skip-message.yaml
    - get_url_bug_fix.yaml
    - lxd-idempotent-config.yaml
    - nicer_multi_error.yml
    - nios_api_duplicate_record-fix.yaml
    - openstack_inventory-optional-region.yaml
    - openvswitch_db_column_value_type.yaml
    - slack_callback_invocation.yaml
    - v2.6.3_summary.yaml
    - vars_prompt-allow-prompting-for-play-vars.yaml
    - win_domain_controller-netlogon.yaml
    release_date: '2018-08-16'
