---
name: ðŸ› Bug report
description: Create a report to help us improve

body:
- type: markdown
  attributes:
    value: |
      âš 
      Verify first that your issue is not [already reported on GitHub][issue search].
      Also test if the latest release and devel branch are affected too.
      *Complete **all** sections as described, this form is processed automatically.*

      [issue search]: https://github.com/ansible/ansible/search?q=is%3Aissue&type=issues


- type: textarea
  attributes:
    label: Summary
    description: Explain the problem briefly below.
    placeholder: >-
      When I try to do X with ansible-core from the devel branch on GitHub, Y
      breaks in a way Z under the env E. Here are all the details I know
      about this problem...
  validations:
    required: true

- type: dropdown
  attributes:
    label: Issue Type
    # FIXME: Once GitHub allows defining the default choice, update this
    options:
    - Bug Report
  validations:
    required: true

- type: input
  attributes:
    label: Component Name
    description: >-
      Write the short name of the module, plugin, task or feature below,
      *use your best guess if unsure*.
    placeholder: dnf, apt, yum, pip, user etc.
  validations:
    required: true

- type: textarea
  attributes:
    label: Ansible Version
    description: >-
      Paste verbatim output from `ansible --version` below, under
      the prompt line. Please don't wrap it with tripple backticks.
    render: console
    value: |
      $ ansible --version
    placeholder: |
      $ ansible --version
      ansible [core 2.11.0b4.post0]  (detached HEAD ref: refs/) last updated 2021/04/02 00:33:35 (GMT +200)
        config file = None
        configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
        ansible python module location = ~/src/github/ansible/ansible/lib/ansible
        ansible collection location = ~/.ansible/collections:/usr/share/ansible/collections
        executable location = bin/ansible
        python version = 3.9.0 (default, Oct 26 2020, 13:08:59) [GCC 10.2.0]
        jinja version = 2.11.3
        libyaml = True
  validations:
    required: true

- type: textarea
  attributes:
    label: Configuration
    description: >-
      Paste verbatim output from `ansible-config dump --only-changed`
      below, under the prompt line.
      Please don't wrap it with tripple backticks.
    render: console
    value: |
      $ ansible-config dump --only-changed
    placeholder: |
      $ ansible-config dump --only-changed
      DEFAULT_GATHERING(~/src/github/ansible/ansible/ansible.cfg) = smart
      DEFAULT_HOST_LIST(~/src/github/ansible/ansible/ansible.cfg) = ['~/src/github/ansible/ansible/hosts']
      DEFAULT_VAULT_PASSWORD_FILE(~/src/github/ansible/ansible/ansible.cfg) = ~/src/github/ansible/ansible/vault/print-password.sh
  validations:
    required: true

- type: textarea
  attributes:
    label: OS / Environment
    description: >-
      Provide all relevant information below, e.g. target OS versions,
      network device firmware, etc.
    placeholder: RHEL 8, CentOS Stream etc.
  validations:
    required: true


- type: textarea
  attributes:
    label: Steps to Reproduce
    description: |
      Describe exactly how to reproduce the problem, using a minimal test-case. It would *really* help us understand your problem if you could also pased any playbooks, configs and commands you used.

      **HINT:** You can paste https://gist.github.com links for larger files.
    value: |
      <!--- Paste example playbooks or commands between quotes below -->
      ```yaml (paste below)

      ```
  validations:
    required: true

- type: textarea
  attributes:
    label: Expected Results
    description: >-
      Describe what you expected to happen when running the steps above.
    placeholder: >-
      I expected X to happen because I assumed Y and was shocked
      that it did not.
  validations:
    required: true

- type: textarea
  attributes:
    label: Actual Results
    description: |
      Describe what actually happened. If possible run with extra verbosity (`-vvvv`).

      Paste verbatim command output and don't wrap it with tripple backticks.
    render: console
  validations:
    required: true


- type: checkboxes
  attributes:
    label: Code of Conduct
    description: |
      Read the [Ansible Code of Conduct][CoC] first.

      [CoC]: https://docs.ansible.com/ansible/latest/community/code_of_conduct.html?utm_medium=github&utm_source=issue_form--bug_report.yml
    options:
    - label: I agree to follow the Ansible Code of Conduct
      required: true
...
