minor_changes:
  - worker process - When controller and forked child workers must share a TTY, the ``WORKER_SESSION_ISOLATION`` config item can be set to ``false``
    (via variable/config/envvar) to disable forked worker session isolation.
