deprecated_features:
  - Templar - direct access to the ``Templar.environment`` attribute is deprecated, consider using ``Templar.copy_with_new_env`` or passing ``overrides`` to ``Templar.template`` instead.
