minor_changes:
  - internals - optimize playbook objects' copy mechanisms in order to reduce overhead from redundant copies of blocks and tasks during playbook execution (https://github.com/ansible/ansible/pull/86936)
