STATE_running = "Running"
STATE_shutdown = "Shut down"
STATE_paused = "Paused"
STATE_restarting = "Restarting"
STATE_resuming = "Resuming"
STATE_creating = "Creating"
STATE_deleting = "Deleting"

ACTION_started = "started"
ACTION_shutdown = "shutdown"
ACTION_stopped = "stopped"
ACTION_restarted = "restarted"
ACTION_force_restarted = "force-restarted"
ACTION_paused = "paused"
ACTION_absent = "absent"
ACTION_resumed = "resumed"
