# -*- coding:utf-8 -*-

commonInfoStr = {}
commonInfoStr['cn'] = {
	#/*Login Strings*/
	'STR_LOGINWELCOME': "请输入您的用户名和密码",
	'STR_LOGINFAILED': "登录失败。请重试。",
	'STR_LOGIN_ERROR': "无效的认证",
	'STR_LOGIN_NOACCESS': "没有权限的用户",
	'STR_LOGIN_BWSRNOTSPRT': "不支持的浏览器",
	'STR_LOGIN_BWSRMSG': "该软件不支持此版本。请检查用户指南支持的浏览器",
	'STR_LOGIN_SESSION_EXPIRED': "会话过期，请重新登录！",
	'STR_LOGIN': "需要认证",
	'STR_LOGIN_ERROR_3': "已在使用中的最大会话数",
	'STR_USER_REQUIRED': "需要用户名",
	'STR_PWD_REQUIRED': "需要密码",
	'STR_COOKIES_ENABLE': "请启用Cookie以便能登录到系统",
	'STR_FIRST_COOKIES_BLOCK': "启用 Cookie，第一方Cookie仍然受阻",
	'STR_USER_ROLE_ERROR': "无法得到用户的角色",
	'STR_LAN_CHANNEL_ERROR': "无法检索局域网通道信息",
	'STR_PROJECT_CFG_ERROR': "无法检索项目配置",
	'STR_USER_LENGTH': "用户名长度不能超过800字符",
	'STR_PWD_LENGTH': "密码长度不能超过300字符",
	'UID':"UID 状态",
	'activeSession':"在线用户信息",
	'diagnosis':"诊断",
	'userManage':"用户管理",
	'sysadmin':"系统管理员",
	'localUser':"本地用户",
	'DirGroup':"目录组",
	'shk':"SSH Key",
	'sslC':"SSL 证书",
	'ldapSet':"LDAP 设置",
	'adSet':"AD 设置",
	'sso':"单点登录",
	'loginSB':"登录安全标题",
	'security':"安全",
	'openFile':"打开文件 ...",
	'illegalInput':"输入不合理，请输入从1开始的数字",
	'videoTitle':"视频日志",

	#alert
	'alertTitle': "告警设置",
	'alertNote': "管理模块的告警设置",
	'tagSnmpName':"SNMP告警",
	'tagEmailName': "邮件告警",
	'strSnmpSuppot': "SNMP告警支持",
	'strSnmpDestAddr': "告警目标地址",
	'strSnmpAlertLev': "SNMP告警等级",
	'STR_CONF_SNMP_GETVAL': "获取SNMP配置参数时发生了一个问题",
	'STR_CONF_SNMP_SETVAL': "设置SNMP配置参数时发生了一个问题",
	'STR_CONF_SNMP_CONFIRM': "您确定要修改SNMP配置信息吗？",
	'STR_CONF_SNMP_SAVE_SUCCESS': "SNMP配置参数保存成功",

	#network
	'STR_CONF_NW_GETVAL': "获取网络配置信息时发生了一个问题",
	'STR_CONF_NW_SETVAL': "设置网络配置信息时发生了一个问题",
	'STR_CONF_NW_GETERR1': "无法获得网络设置",
	'STR_CONF_NW_SETERR1': "无法设置提供的网络参数",
	'STR_CONF_NW_SAVE_CONFIRM': "此功能可能会改变设备的IP地址，你可能会失去在这个浏览器会话的连接。更改后，请使用新的浏览器会话。你要继续吗？",
	'STR_CONF_NW_RESET_TITLE': "网络配置已复位",
	'STR_CONF_NW_RESET_DESC': "网络配置已成功。这将需要几秒钟重新生效新接口。请关闭此浏览器会话，并打开一个新的浏览器会话连接新的IP设备。",
	'STR_CONF_NW_ERR_222': "IP地址或者默认网关超出正常范围",
	'STR_CONF_NW_ERR_223': "无效的IPV4 IP地址",
	'STR_CONF_NW_ERR_224': "无效的IPV4默认网关",
	'STR_CONF_NW_ERR_225': "无效的IPV4子网掩码",
	'STR_CONF_NW_ERR_226': "无效的IPV6 IP地址",
	'STR_CONF_NW_ERR_227': "无效的IPV6默认网关",
	'STR_CONF_NW_ERR_387': "网络接口不能被禁用，因为当前只有一个接口是启用的",
	'STR_CONF_NW_ERR_469': "VLAN ID不能直接更改。想要改变VLAN ID，首先禁用已启用的VLAN配置，修改，然后尝试启用新的VLAN ID的VLAN 配置。",
	'strETH0': "eth0",
	'strETH1': "eth1",
	'strBOND0': "bond0",

	#/*General Strings*/
	'STR_PERMISSION_DENIED': "您的用户权限过低，无法查看此内容！",
	'STR_CONF_ADMIN_PRIV': "执行此动作需要管理员权限",
	'STR_TIME_OUT': "BMC 似乎太长时间没有响应了。请检查电缆。",
	'STR_NOT_CONFIGURE': "没有配置",
	'STR_NOT_AVAILABLE': "不可用",
	'STR_DATA': "数据",
	'STR_NOT_APPLICABLE': "N/A",
	'STR_NOT_SUPPORT': "不支持",
	'STR_NONE': "没有",
	'STR_MANUAL': "手动",
	'STR_AUTO': "自动",
	'STR_BLANK': "&nbsp,",
	'STR_EMPTY': " ",
	'STR_NEWLINE': "\n",
	'STR_HELP': "帮助",
	'STR_AND_ABOVE': "及以上",
	'STR_ANY': "任何",
	'STR_PROCESS_ABORT': "正在进行的处理将被终止",
	'STR_FWFLASH_ABORT': "在固件程序升级过程中关闭Web会话会造成设备重新启动",
	'STR_LOGOUT_SUCCESS': "注销成功",
	'STR_EVENT_ENTRIES': "事件条目",
	'STR_SAVE': "保存",
	'STR_ADD': "增加",
	'STR_MODIFY': "修改",
	'STR_REPLACE': "替换",
	'STR_CANCEL': "取消",
	'STR_ENABLED': "启用",
	'STR_DISABLED': "禁用",
	'STR_HASH': "#",
	'STR_USERNAME': "用户",
	'STR_PASSWORD': "密码",
	'STR_DOMAINNAME': "域名",
	'STR_SERVER_ADDRESS': "服务器地址",
	'STR_SOURCE_PATH': "源路径",
	'STR_RETRY_COUNT': "重新计数",
	'STR_PRESERVE': "保存",
	'STR_OVERWRITE': "改写",
	'STR_INACTIVE': "无效",
	'STR_ACTIVE': "有效",
	'STR_STAND_BY': "备用",
	'STR_YES': "是",
	'STR_NO': "非",
	'STR_NORMAL': "正常",
	'STR_WARNING': "警告",
	'STR_ABNORMAL': "异常",
	'STR_START': "开始",
	'STR_STOP': "结束",

	#/*General Error Strings*/
	'STR_IPMI_ERROR': "IPMI故障：",
	'STR_ERROR_CODE': "代码错误：",
	'STR_HELP_INFO': "参考“帮助”以获得更多信息",
	'STR_INVALID_FIELDS': "以下是无效的字段\n",
	'STR_INVALID_PORT': "无效的端口号",
	'STR_INVALID_IP': "无效的IP地址格式",
	'STR_INVALID_TIMEOUT': "无效的超时",
	'STR_INVALID_SERVERADDR': "无效的服务器地址",
	'STR_INVALID_USERNAME': "无效的用户名",
	'STR_INVALID_PASSWORD': "无效的密码",
	'STR_INVALID_CPWORD': "密码和密码确认不匹配",
	'STR_INVALID_UNAME_PWORD': "用户/密码不能为空",
	'STR_INVALID_EMAILADDR': "无效的电子邮箱地址",
	'STR_INVALID_DOMAIN': "无效的域名",
	'STR_INVALID_SEARCHBASE': "无效的搜索库",
	'STR_INVALID_RGNAME': "角色组名称无效",
	'STR_INVALID_PAGENO': "无效的页号",
	'STR_INVALID_SRC_PATH': "无效源路径",
	'STR_NETWORK_ERROR': "在网络连接上有一些问题",
	'STR_LANG_NOT_FOUND': "浏览器语言无法确定。用英语（美国）默认。",

	#/*General - Confirmation messages*/
	'STR_CONFIRM_DELETE': "如果您想继续删除此条目请点击OK确认",
	'STR_GENERAL_COMMAND_CONFIRM': "您确认执行此条命令？",
	'STR_GENERAL_LOGOUT': "如果您想继续注销请点击OK确认",
	'STR_GENERAL_DISCONNECT': "您确认从此服务器中断开连接",
	'STR_CONSOLE_CONNECTED': "如果存在已经打开的控制台窗口，此窗口将会被关闭。",
	'STR_SSLCERT_ABORT': "上传SSL证书将被中止。",
	'STR_IPMI_LIBRARY_ERROR': "IPMI库没有响应。请检查IPMI进程是否在运行中。",

	'STR_DEVICE_RESET_TITLE': "设备已经复位",
	'STR_DEVICE_RESET_DESC': "设备已经复位。请关闭此浏览器会话，并打开一个新的浏览器会话，重新连接到该设备。设备重启动可能需要1分钟时间。",
	'STR_DEVICE_PREPARE_FAILED_RESET_DESC': "设备准备失败，设备已经复位。请关闭此浏览器会话，并打开一个新的浏览器会话，重新连接到该设备。设备重启动可能需要1分钟时间。",

	'STR_UTC_OFFSET': "UTC偏移量: ",
	'STR_GMT': "(格林威治标准时间",

	'STR_FW_UPDATE_CONFIRM1': "直到完成固件升级和设备重新启动，你将无法执行任何其他任务。如果你想进入更新模式单击“确定”？",
	'STR_FW_UPDATE_CONFIRM2': "您确定终止固件升级吗？设备将被复位以便能够进入到正常运行模式。",
	'STR_FW_UPDATE_CONFIRM3': "新的固件镜像的大小不同于现有固件镜像的大小。在这种情况下，“配置”不能保留。您希望继续吗？",
	'STR_FW_UPDATE_CONFIRM4': "点击“确定”将开始实际的升级操作。存储写入新的固件镜像。它是必不可少的，一旦开始升级操作不能被中断。你想继续吗？",
	'STR_FW_UPDATE_CONFIRM5': "覆盖文件错误，点击“确定”将开始实际的升级操作而不覆盖的文件，存储写入新的固件镜像。它是必不可少的升级操作不能被中断，你想继续吗？",
	'STR_FW_UPDATE_ERR1': "请输入一个有效的镜像文件",
	'STR_FW_UPDATE_ERR2': "镜像验证不成功。请检查您是否上传了正确的镜像文件。",
	'STR_FW_UPDATE_ERR3': "镜像刷新不成功",
	'STR_FW_UPDATE_ERR4': "镜像验证不成功。请检查您是否上传正确signimage公共密钥。",
	'STR_FW_UPDATE_ERR5': "镜像验证不成功。上传的镜像跟平台的不一样。请检查您是否上传了正确的镜像文件。",

	'STR_FW_UPDATE_RESET_CONFIRM': "按Cancle重启设备。按OK重新上传镜像。",
	'STR_FW_UPDATE_RESET': "再次升级时您需要重置设备。按OK确认重置设备。",
	'STR_FW_FLASH_PROGRESS': "正在升级！请稍后再试。",
	'STR_FW_VERIFY_DIFFVERSION': "固件镜像已经验证通过。上传的镜像跟原先的设备固件版本不同。",
	'STR_FW_VERIFY_DIFFSIZE': "固件镜像已经验证通过。上传的镜像大小跟存在的设备固件镜像不一致。",
	'STR_FW_VERIFY_SAME': "固件镜像已经验证通过。",
	'STR_FW_PREPARE_FLASH': "准备设备固件升级时发生了一个问题",
	'STR_FW_DWLDIMG_ERR': "远程服务器下载固件镜像时发生一个问题。请检查您是否有正确的‘固件镜像传输协议‘的配置。",
	'STR_FW_DWLDSTATUS_ERR': "获取固件镜像下载状态时发生一个问题。请检查您是否有正确的‘固件镜像传输协议’的配置。",
	'STR_FW_SIGNKEY_GETVAL': "获取SignImage公共密钥信息时发生了一个问题",
	'STR_FW_SIGNKEY_TITLE': "上传SignImage公共密钥",
	'STR_FW_SIGNKEY_INFO': "以上传SignImage公共密钥",
	'STR_FW_NEW_SIGN_KEY': "新的SignImage公共密钥",
	'STR_FW_SIGNKEY_INVALID1': "请输入SignImage公共密钥文件",
	'STR_FW_SIGNKEY_INVALID2': "SignImage公共密钥文件名称应该以.pem结尾",
	'STR_FW_SIGNKEY_SUCCESS': "SignImage公共密钥上传成功",
	'STR_FW_SIGNKEY_ERR1': "SignImage公共密钥文件不存在",
	'STR_FW_SIGNKEY_ERR3': "SignImage公共密钥验证失败。请重新上传SignImage公共密钥。",
	'STR_FW_SIGNKEY_ERR4': "上传SignImage公共密钥失败。请重新上传。",
	'STR_FW_SIGNKEY_ERR5': "signimage公钥文件的大小超出限制",
	'STR_FW_SIGNKEY_VALIDATE_ERR': "signimage公共密钥验证时发生了一个问题",
	'STR_FW_PRSRV_CFG_DESC': "与个人无关的条目在下面的表格中被标记成保存/改写状态",
	'STR_FW_FLASH_IMAGE': "刷新镜像",
	'STR_FW_BOOT_IMAGE': "启动镜像",
	'STR_FW_REBOOT_BMC': "固件刷新成功后重启BMC",

	'STR_APP_STR_ALL_DEASSERTED': "全部解除",
	'LAN_INTERFACE_NAME_BY_INDEX':["共享管理口","专用管理口","bond0"],
	'refresh':"刷新",
	'save':"保存",
	'reset':"复位",
	'enable': "启用",
	'inactive':"无效",
	'active':"有效",
	'notApplicable':"N/A",
	'modify':"修改",
	'add':"增加",
	'srvactive':"激活",
	'cancel':"取消",
	'STR_EXPORT_LOG':"导出日志",
	'STR_CLEAR_LOG':"清除日志",
	'STR_IMG_INFO':"信息",
	'STR_IMG_ON':"开机/在位/冗余",
	'STR_IMG_ON_1':"在位",
	'STR_IMG_ON_2':"连通",
	'STR_IMG_ON_3':"在位/连通",
	'STR_IMG_CRITICAL':"严重",
	'STR_IMG_ABSENT':"关机/不在位/不可用/不冗余",
	'STR_IMG_ABSENT_1':"不在位",
	'STR_IMG_ABSENT_2':"不可用",
	'STR_IMG_ABSENT_3':"不在位/断开",
	'STR_IMG_WARNING':"警告",
	'STR_IMG_OK':"正常",
	'STR_IMG_OK_1':"正常/定位/重建",
	'STR_IMG_UNSPORRT':"不支持",
	'STR_NOTE':"说明:",
	'STR_ATTRIBUTE':"属性",
	'STR_VALUE':"值",
	'confirmAction':"确认执行此操作？",
	'confirmActionOK':"操作执行成功!",
	'confirmActionFAIL':"操作执行失败!",
	'STR_BIOS_IO_TITLE':"BIOS 配置",
	'STR_BIOS_IO_EX':"导出配置文件",
	'STR_BIOS_IO_UP':"上传配置文件",
	'STR_BIOS_IO_File':"选择要上传的配置文件",
	'STR_BIOS_IO_UP_SU':"上传文件成功",
	'STR_BIOS_IO_UP_FI':"上传文件失败",
	'preserveCFG':[
		{'name':"SDR",'value':"sdr"},
		#{name:"FRU",value:"fru"},
		{'name':"SEL",'value':"sel"},
		{'name':"IPMI",'value':"ipmi"},
		{'name':"PEF",'value':"pef"},
		{'name':"SOL",'value':"sol"},
		{'name':"SMTP",'value':"smtp"},
		{'name':"User",'value':"user"},
		{'name':"DCMI",'value':"dcmi"},
		{'name':"Network",'value':"network"},
		{'name':"NTP",'value':"ntp"},
		{'name':"SNMP",'value':"snmp"},
		{'name':"SSH",'value':"ssh"},
		{'name':"KVM",'value':"kvm"},
		{'name':"Authentication",'value':"authentication"},
		{'name':"Syslog",'value':"syslog"},
		{'name':"Hostname",'value':"hostname"}

	],
	'videoTableHeader':[
		'序号',
		'时间戳',
		'文件名'
	],
	'STR_CLEAR_VIDEO_EMPTY':"	当前没有视频日志，无法进行清除",
	'clearNote':"您确定要清除日志吗?",
	'clearSuccess':"清除日志成功",
	'clearFail':"清除日志失败!",
	'wrongStr':"输入不合法或为空"




}
commonInfoStr["cn"]["LAN_INTERFACE_NAME_BY_LAN_CH"] = {};
commonInfoStr["cn"]["LAN_INTERFACE_NAME_BY_LAN_CH"][0] =commonInfoStr["cn"]["STR_MANUAL"];
commonInfoStr["cn"]["LAN_INTERFACE_NAME_BY_LAN_CH"][1] =commonInfoStr["cn"]["LAN_INTERFACE_NAME_BY_INDEX"][1];
commonInfoStr["cn"]["LAN_INTERFACE_NAME_BY_LAN_CH"][8] =commonInfoStr["cn"]["LAN_INTERFACE_NAME_BY_INDEX"][0];
#chenqiuyi_20160119 for lan channel change ++<<
commonInfoStr["cn"]["LAN_INTERFACE_NAME_BY_LAN_CH"]["eth1"] =commonInfoStr["cn"]["LAN_INTERFACE_NAME_BY_INDEX"][1];
commonInfoStr["cn"]["LAN_INTERFACE_NAME_BY_LAN_CH"]["eth0"] =commonInfoStr["cn"]["LAN_INTERFACE_NAME_BY_INDEX"][0];
commonInfoStr["cn"]["LAN_INTERFACE_NAME_BY_LAN_CH"]["bond0"]=commonInfoStr["cn"]["LAN_INTERFACE_NAME_BY_INDEX"][2];
commonInfoStr['en'] = {
	#/*Login Strings*/
	'STR_LOGINWELCOME':"Please type your user name and password",
	'STR_LOGINFAILED':"Login failed. Please try again",
	'STR_LOGIN_ERROR':"Invalid Authentication",
	'STR_LOGIN_NOACCESS':"No Privilege user",
	'STR_LOGIN_BWSRNOTSPRT':"NOT SUPPORTED BROWSER",
	'STR_LOGIN_BWSRMSG':"This software does not support this browser version.Please check User\'s Guide for supported browsers.",

	'STR_LOGIN_SESSION_EXPIRED':"Session expired, please relogin!",
	'STR_LOGIN':"Authentication Required",
	'STR_LOGIN_ERROR_3':"Maximum number of sessions already in use",
	'STR_USER_REQUIRED': "Username is required",
	'STR_PWD_REQUIRED': "Password is required",
	'STR_COOKIES_ENABLE': "Please enable the cookies in order to log into the system",
	'STR_FIRST_COOKIES_BLOCK': "Cookies are enabled, First party cookies are still blocked",
	'STR_USER_ROLE_ERROR': "Couldn\'t get role for the user",
	'STR_LAN_CHANNEL_ERROR': "Couldn\'t retrieve lan channel information",
	'STR_PROJECT_CFG_ERROR': "Couldn\'t retrieve project configuration",
	'STR_USER_LENGTH': "Username length cannot exceed more than 800 characters",
	'STR_PWD_LENGTH': "Password length cannot exceed more than 300 characters",
	'UID':"UID State",
	'activeSession':"Active Session",
	'diagnosis':"Diagnostics",
	'userManage':"User Administration",
	'sysadmin':"System Administrator",
	'localUser':"Local Users",
	'DirGroup':"Directory Group",
	'shk':"SSH Key",
	'sslC':"SSL Certificate",
	'ldapSet':"LDAP Settings",
	'adSet':"AD Settings",
	'sso':"SSO",
	'loginSB':"Login Security Banner",
	'security':"Security",
	'openFile':"open file...",
	'illegalInput':"Unreasonable input,please enter a number starting from 1 ",
	'videoTitle':"Video Log",

	#alert
	'alertTitle': "Alert Settings",
	'alertNote': "Manage Alert Settings.",
	'tagSnmpName':"SNMP Alert",
	'tagEmailName': "Email Alert",
	'strSnmpSuppot': "SNMP Alert Support",
	'strSnmpDestAddr': "Destination Address",
	'strSnmpAlertLev': "SNMP Alert Level",
	'STR_CONF_SNMP_GETVAL': "There was a problem while getting SNMP configuration.",
	'STR_CONF_SNMP_SETVAL': "There was a problem while setting SNMP configuration.",
	'STR_CONF_SNMP_CONFIRM': "Are you sure you want to Configure SNMP?",
	'STR_CONF_SNMP_SAVE_SUCCESS': "SNMP Alert configuration has been modified successfully.",

	#network
	'STR_CONF_NW_GETVAL': "There was a problem while getting Network configuration",
	'STR_CONF_NW_SETVAL': "There was a problem while setting Network configuration.\n",
	'STR_CONF_NW_GETERR1': "Could not get network settings",
	'STR_CONF_NW_SETERR1': "Unable to set the supplied network parameters ",
	'STR_CONF_NW_SAVE_CONFIRM': "This function may change the IP address of the device, and you may lose connectivity in this browser session.\nPlease reconnect using a new browser session after applying the changes.\nDo you want to proceed?",
	'STR_CONF_NW_RESET_TITLE': "Network configuration has been reset",
	'STR_CONF_NW_RESET_DESC': "Network configuration has been set successfully. It will take few seconds to bring up the interface again. Please close this browser session and open a new browser session to connect to the device with new IP. ",
	'STR_CONF_NW_ERR_222': "Either IP Address or Default Gateway IP is out of range.",
	'STR_CONF_NW_ERR_223': "Invalid IPv4 IP Address",
	'STR_CONF_NW_ERR_224': "Invalid IPv4 Default Gateway",
	'STR_CONF_NW_ERR_225': "Invalid IPv4 Subnet mask",
	'STR_CONF_NW_ERR_226': "Invalid IPv6 IP Address",
	'STR_CONF_NW_ERR_227': "Invalid IPv6 Default Gateway",
	'STR_CONF_NW_ERR_387': "Network interface cannot be disabled, as only one interface is currently enabled.",
	'STR_CONF_NW_ERR_469': "VLAN ID cannot be changed directly. To change the VLAN ID, disable the already enabled VLAN configuration, then try enabling the VLAN configuration with the new VLAN ID.",
	'strETH0': "eth0",
	'strETH1': "eth1",
	'strBOND0': "bond0",

	#/*General Strings*/
	'STR_PERMISSION_DENIED': "Permission denied to view this content.",
	'STR_CONF_ADMIN_PRIV': "You need to have administrator privileges to perform this action.",
	'STR_TIME_OUT': "The BMC seems to be taking too long to respond. Please check the cables and configuration",
	'STR_NOT_CONFIGURE': "Not Configured",
	'STR_NOT_AVAILABLE': "Not Available",
	'STR_DATA': "Data ",
	'STR_NOT_APPLICABLE': "N/A",
	'STR_NOT_SUPPORT':"Not Supported",
	'STR_NONE': "None",
	'STR_MANUAL': "Manual",
	'STR_AUTO': "Automatic",
	'STR_BLANK': "&nbsp,",			# Empty string
	'STR_EMPTY': " ",			# Empty string
	'STR_NEWLINE': "\n",
	'STR_HELP': "HELP",
	'STR_AND_ABOVE': " and Above",
	'STR_ANY': "Any",
	'STR_PROCESS_ABORT': "Ongoing process will be aborted.",
	'STR_FWFLASH_ABORT': "Closing the web session during firmware flash causes device to be restarted.",
	'STR_LOGOUT_SUCCESS': "You have been logged out successfully.",
	'STR_EVENT_ENTRIES':" Event entries",
	'STR_SAVE': "Save",
	'STR_ADD': "Add",
	'STR_MODIFY': "Modify",
	'STR_REPLACE': "Replace",
	'STR_CANCEL': "Cancel",
	'STR_ENABLED': "Enabled",
	'STR_DISABLED': "Disabled",
	'STR_HASH': "#",
	'STR_USERNAME': "Username",
	'STR_PASSWORD': "Password",
	'STR_DOMAINNAME': "Domain Name",
	'STR_SERVER_ADDRESS': "Server Address",
	'STR_SOURCE_PATH': "Source Path",
	'STR_RETRY_COUNT': "Retry Count",
	'STR_PRESERVE': "Preserve",
	'STR_OVERWRITE': "Overwrite",
	'STR_INACTIVE': "Inactive ",
	'STR_ACTIVE': "Active",
	'STR_STAND_BY': "Stand-by",
	'STR_YES': "Yes",
	'STR_NO': "No",
	'STR_NORMAL':'Normal',
	'STR_WARNING':"Warning",
	'STR_ABNORMAL':"Abnormal",
	'STR_START':"Start",
	'STR_STOP':"Stop",

	#/*General Error Strings*/
	'STR_IPMI_ERROR':"  IPMI ERROR:",
	'STR_ERROR_CODE': "  Error Code : ",
	'STR_HELP_INFO': " Refer \'Help\' for more Information.",
	'STR_INVALID_FIELDS': "Following are the Invalid field(s),\n",
	'STR_INVALID_PORT': "Invalid Port Number",
	'STR_INVALID_IP':"Invalid IP Address format.",
	'STR_INVALID_TIMEOUT': "Invalid Time Out.",
	'STR_INVALID_SERVERADDR': "Invalid Server Address.",
	'STR_INVALID_USERNAME': "Invalid Username.",
	'STR_INVALID_PASSWORD': "Invalid Password.",
	'STR_INVALID_CPWORD': "Password and confirmation password do not match",
	'STR_INVALID_UNAME_PWORD': "Username/Password cannot be blank",
	'STR_INVALID_EMAILADDR': "Invalid Email Address.",
	'STR_INVALID_DOMAIN':"Invalid Domain Name.",
	'STR_INVALID_SEARCHBASE': "Invalid Search base.",
	'STR_INVALID_RGNAME':"Invalid Role Group Name.",
	'STR_INVALID_PAGENO':"Invalid Page Number.",
	'STR_INVALID_SRC_PATH': "Invalid Source Path.",
	'STR_NETWORK_ERROR':"There is some problem in network connection.",
	'STR_LANG_NOT_FOUND': "Browser language could not be determined. Using English(US) by default.",


	#/*General - Confirmation messages*/
	'STR_CONFIRM_DELETE': "Click OK if you want to continue deleting this entry.",
	'STR_GENERAL_COMMAND_CONFIRM': "Are you sure to execute this command？",
	'STR_GENERAL_LOGOUT': "Click OK if you want to continue logging out.",
	'STR_GENERAL_DISCONNECT': "Are you sure to disconnect from this server",
	'STR_CONSOLE_CONNECTED': "If exist, the Active Console Window will be closed.",
	'STR_SSLCERT_ABORT': "SSL certificate upload will be aborted.",
	'STR_IPMI_LIBRARY_ERROR': "IPMI library not responding. Please check if the IPMI process is running.",

	'STR_DEVICE_RESET_TITLE': "Device has been reset",
	'STR_DEVICE_RESET_DESC': "The device has been reset. Please close this browser session and open a new browser session to reconnect to the device. The device may take about a minute to boot up.",
	'STR_DEVICE_PREPARE_FAILED_RESET_DESC': "Fail to enter update mode ，the device has been reset. Please close this browser session and open a new browser session to reconnect to the device. The device may take about a minute to boot up.",
	'STR_UTC_OFFSET': "UTC Offset",
	'STR_GMT': "(GMT",

	#/*Firmware Update*/
	'STR_FW_UPDATE_CONFIRM1':"You will not be able to perform any other tasks until firmware upgrade is complete and the device is rebooted. Click Ok if you want to enter the update mode?",
	'STR_FW_UPDATE_CONFIRM2':"Are you sure to abort the firmware upgrade process? The device will have to be reset in order to go back to normal operating mode",
	'STR_FW_UPDATE_CONFIRM3':"New firmware image size is different from the existing firmware image size. \'Configuration\' can not be preserved in this situation. Do you want to continue?",
	'STR_FW_UPDATE_CONFIRM4':"Clicking \'OK\' will start the actual upgrade operation, where the storage is written with the new firmware image. It is essential that the upgrade operation is not interrupted once it starts. Do you wish to proceed?",
	'STR_FW_UPDATE_CONFIRM5':"Error in overwriting the files, Clicking \'OK\' will start the actual upgrade operation without overwrite the files, where the storage is written with the new firmware image. It is essential that the upgrade operation is not interrupted once it starts. Do you wish to proceed?",
	'STR_FW_UPDATE_ERR1': "Please enter a valid image file",
	'STR_FW_UPDATE_ERR2': "Image Verification unsuccessful. Please check if you uploaded the correct Image.",
	'STR_FW_UPDATE_ERR3': "Image Flashing unsuccessful.",
	'STR_FW_UPDATE_ERR4': "Image Verification unsuccessful. Please check if you uploaded the correct SignImage Public Key.",
	'STR_FW_UPDATE_ERR5': "Image Verification unsuccessful. The image uploaded is for different platform. Please check if you uploaded the correct Image.",

	'STR_FW_UPDATE_RESET_CONFIRM': "Press Cancle to reset the device now. Press OK to reload image.",
	'STR_FW_UPDATE_RESET': " In order to try upgrading again you need to reset the device. Press OK to reset the device now.",
	'STR_FW_FLASH_PROGRESS': "Flash is in Progress! Please try later",
	'STR_FW_VERIFY_DIFFVERSION': "The firmware image has been verified. The uploaded image is a different version of the existing device firmware.",
	'STR_FW_VERIFY_DIFFSIZE': "The firmware image has been verified. The uploaded image size is different from the existing device firmware.",
	'STR_FW_VERIFY_SAME': "The firmware image has been verified. The uploaded image appears to be the same as the existing device firmware.",
	'STR_FW_PREPARE_FLASH': "There was a problem while preparing device for firmware upgrade.",
	'STR_FW_DWLDIMG_ERR': "There was a problem while downloading firmware image from remote server. Please check if you have given the correct \'Firmware Image Transfer Protocol\' configuration.",
	'STR_FW_DWLDSTATUS_ERR': "There was a problem while getting download status of firmware image. Please check if you have given the correct \'Firmware Image Transfer Protocol\' configuration.",

	'STR_FW_SIGNKEY_GETVAL': "There was a problem while getting SignImage public key information.",
	'STR_FW_SIGNKEY_TITLE': "Upload  SignImage Public Key",
	'STR_FW_SIGNKEY_INFO': "Uploaded  SignImage Public Key",
	'STR_FW_NEW_SIGN_KEY': "New SignImage Public Key",
	'STR_FW_SIGNKEY_INVALID1': "Please enter a SignImage Public key file",
	'STR_FW_SIGNKEY_INVALID2': "SignImage Public key file name should end with .pem",
	'STR_FW_SIGNKEY_SUCCESS': "SignImage Public Key uploaded successfully",
	'STR_FW_SIGNKEY_ERR1': "The SignImage Public Key file does not exists",
	'STR_FW_SIGNKEY_ERR3': "The SignImage Public Key validation failed. Please try to upload the SignImage Public Key again.",
	'STR_FW_SIGNKEY_ERR4': "Uploading SignImage Public Key failed. Please try uploading the SignImage Public Key again.",
	'STR_FW_SIGNKEY_ERR5': "The SignImage Public Key file size exceeds",
	'STR_FW_SIGNKEY_VALIDATE_ERR': "There was a problem while validating SignImage Public Key",
	'STR_FW_PRSRV_CFG_DESC': " - irrespective of the individual items marked as preserve/overwrite in the table below."    ,

	'STR_FW_FLASH_IMAGE': "Flash Image",
	'STR_FW_BOOT_IMAGE': "Boot Image",
	'STR_FW_REBOOT_BMC': "Reboot BMC after Firmware flash",

	'STR_APP_STR_ALL_DEASSERTED': "All deasserted",
	'LAN_INTERFACE_NAME_BY_INDEX':["Shared","Dedicated","bond0"],


	'refresh':"Refresh",
	'save':"Save",
	'reset':"Reset",
	'enable': "Enable",
	'cancel':"Cancel",

	'inactive':"Inactive",
	'active':"Active",
	'notApplicable':"N/A",
	'modify':"Modify",
	'add':"Add",
	'srvactive':"Active",
	'STR_EXPORT_LOG':"Export Log",
	'STR_CLEAR_LOG':"Clear Log",
	'STR_IMG_INFO':"Information",
	'STR_IMG_ON':"Power On/Present/Redundant",
	'STR_IMG_ON_1':"Present",
	'STR_IMG_ON_2':"Linkup",
	'STR_IMG_ON_3':"Present/Linkup",
	'STR_IMG_CRITICAL':"Critical",
	'STR_IMG_ABSENT':"Power Off/Absent/NA/No-Redundant",
	'STR_IMG_ABSENT_1':"Absent",
	'STR_IMG_ABSENT_2':"N/A",
	'STR_IMG_ABSENT_3':"Absent/Linkdown",
	'STR_IMG_WARNING':"Warning",
	'STR_IMG_OK':"Normal",
	'STR_IMG_OK_1':"Normal/Location/Rebuild",
	'STR_IMG_UNSPORRT':"Not Support",
	'STR_NOTE':"Note:",
	'STR_ATTRIBUTE':"Attribute",
	'STR_VALUE':"Value",
	'confirmAction':"Confirm to perform this action?",
	'confirmActionOK':"Succeed to perform the action!",
	'confirmActionFAIL':"Failed to perform the action!",
	'STR_BIOS_IO_TITLE':"BIOS Settins",
	'STR_BIOS_IO_EX':"Export The Settings File",
	'STR_BIOS_IO_UP':"Upload The Settings File",
	'STR_BIOS_IO_File':'Select the file',
	'STR_BIOS_IO_UP_SU':"The file has been successfully uploaded",
	'STR_BIOS_IO_UP_FI':"The performance was failed",
	'preserveCFG':[
		{'name':"SDR",'value':"sdr"},
		#{name:"FRU",value:"fru"},
		{'name':"SEL",'value':"sel"},
		{'name':"IPMI",'value':"ipmi"},
		{'name':"PEF",'value':"pef"},
		{'name':"SOL",'value':"sol"},
		{'name':"SMTP",'value':"smtp"},
		{'name':"User",'value':"user"},
		{'name':"DCMI",'value':"dcmi"},
		{'name':"Network",'value':"network"},
		{'name':"NTP",'value':"ntp"},
		{'name':"SNMP",'value':"snmp"},
		{'name':"SSH",'value':"ssh"},
		{'name':"KVM",'value':"kvm"},
		{'name':"Authentication",'value':"authentication"},
		{'name':"Syslog",'value':"syslog"},
		{'name':"Hostname",'value':"hostname"}

	],
	'videoTableHeader':[
		'ID',
		'Time Stamp',
		'Name'
	],
	'STR_CLEAR_VIDEO_EMPTY':"No Video Log available, no need to clear!",
	'clearNote':"Are you sure to clear Log?",
	'clearSuccess':"Succeed to clear log",
	'clearFail':"Fail to clear log!",
	'wrongStr':"input is illegal or null"

}
commonInfoStr["en"]["LAN_INTERFACE_NAME_BY_LAN_CH"] = {}
commonInfoStr["en"]["LAN_INTERFACE_NAME_BY_LAN_CH"][0] =commonInfoStr["en"]["STR_MANUAL"]
commonInfoStr["en"]["LAN_INTERFACE_NAME_BY_LAN_CH"][1] =commonInfoStr["en"]["LAN_INTERFACE_NAME_BY_INDEX"][1];
commonInfoStr["en"]["LAN_INTERFACE_NAME_BY_LAN_CH"][8] =commonInfoStr["en"]["LAN_INTERFACE_NAME_BY_INDEX"][0];
#chenqiuyi_20160119 for lan channel change ++<<
commonInfoStr["en"]["LAN_INTERFACE_NAME_BY_LAN_CH"]["eth1"] =commonInfoStr["en"]["LAN_INTERFACE_NAME_BY_INDEX"][1];
commonInfoStr["en"]["LAN_INTERFACE_NAME_BY_LAN_CH"]["eth0"] =commonInfoStr["en"]["LAN_INTERFACE_NAME_BY_INDEX"][0];
commonInfoStr["en"]["LAN_INTERFACE_NAME_BY_LAN_CH"]["bond0"] =commonInfoStr["en"]["LAN_INTERFACE_NAME_BY_INDEX"][2];

#chenqiuyi_20160119 for lan channel change ++>>
