[ClassVersion("{{item.version}}")]
class ANSIBLE_xTestClass
{
    [Write] String StringKey;
    [Write] Boolean BooleanKey;
    [Write] UInt32 UInt32Key;
    [Write] String StringArrayKey[];
};

[ClassVersion("{{item.version}}"), FriendlyName("xTestResource")]
class ANSIBLE_xTestResource : OMI_BaseResource
{
    [Key] String Path;
    [Required, ValueMap{"Present", "Absent"}, Values{"Present", "Absent"}] String Ensure;
    [Write] String StringParam;
    [Write] UInt32 UInt32Param;
    [Write] UInt64 UInt64Param;
    [Write] String StringArrayParam[];
    [Write] UInt32 UInt32ArrayParam[];
    [Write] UInt64 UInt64ArrayParam[];
    [Write] Boolean BooleanParam;
    [Write, EmbeddedInstance("MSFT_Credential")] String PSCredentialParam;
    [Write, EmbeddedInstance("ANSIBLE_xTestClass")] String CimInstanceParam;
    [Write, EmbeddedInstance("ANSIBLE_xTestClass")] String CimInstanceArrayParam[];
};
