ansible(1)
=========
:doctype:manpage
:man source:   Ansible
:man version:  0.0.1
:man manual:   System administration commands

NAME
----
ansible - run a command somewhere else


SYNOPSIS
--------
ansible [-f forks] [-p pattern ] [-u remote_user]
        [-n module_name] [-a [args1 [args2 ...]]]


DESCRIPTION
-----------

*Ansible* is an extra-simple tool/framework/API for doing \'remote things' over
SSH.


OPTIONS
-------

*-k*, *--ask-pass*::

Ask the user to input the ssh password for connecting.  Generally using
ssh-agent instead is preferred.


*-l*, *--host-list*::

Path to hosts list, which defaults to /etc/ansible/hosts.  Users can use
multiple files to emulate groups of systems.


*-m*, *--module-path*::

Override the path to module library, which defaults to /usr/share/ansible.
The module library contains runnable modules that do 'things' to remote
hosts.  See ansible-modules(5) for a list of those that bundled with
Ansible.


*-f*, *--forks*::

Level of parallelism. Specify as an integer, the default is 3.  If set to "1" 
debugging for certain classes of internal errors may become easier.


*-n*, *--name*::

Module name to execute.


*-a*, *--args*::

Arguments to module, as a single string.  Be sure to observe proper shell quoting rules.
How these are handled are up to the module, but most modules take "key=value" pairs
delimited by spaces.


*-p*, *--pattern*::

Hostname pattern. Accepts shell-like globs which can be seperated with ";"
The default is "*" which matches all hosts in the ansible hosts file.


*-u*, *--remote-user*::

Remote user to connect as. Uses __root__ by default.


INVENTORY
---------

Ansible stores the hosts it can potentially operate on in an inventory
file. The syntax is simple: one host per line. Organize your hosts
into multiple groups by separating them into multiple inventory files.


FILES
-----

/etc/ansible/hosts -- Default hosts file

/usr/share/ansible -- Default module library


AUTHOR
------

Ansible was originally written by Michael DeHaan. See the AUTHORS file
for a complete list of contributors.


COPYRIGHT
---------

Copyright © 2012, Michael DeHaan

Ansible is released under the terms of the GPLv3 License.


SEE ALSO
--------

*ansible-modules*(5), 

*ansible-playbook*(5),

Ansible home page: <https://github.com/mpdehaan/ansible/>
