trigger:
  batch: true
  branches:
    include:
      - devel
      - stable-*

pr:
  autoCancel: true
  branches:
    include:
      - devel
      - stable-*

schedules:
  - cron: 0 7 * * *
    displayName: Nightly
    always: true
    branches:
      include:
        - devel
        - stable-*

variables:
  - name: checkoutPath
    value: ansible
  - name: coverageBranches
    value: devel
  - name: entryPoint
    value: .azure-pipelines/commands/entry-point.sh
  - name: fetchDepth
    value: 500
  - name: defaultContainer
    value: quay.io/ansible/azure-pipelines-test-container:6.0.0

pool: Standard

stages:
  - stage: c7a
    dependsOn: []
    jobs:
      - template: templates/matrix.yml  # context/target
        parameters:
          targets:
            - name: RHEL 9.5 py39
              test: rhel/9.5@3.9
            - name: RHEL 9.5 py312
              test: rhel/9.5@3.12
            - name: FreeBSD 13.4
              test: freebsd/13.4
            - name: FreeBSD 14.2
              test: freebsd/14.2
          groups:
            - c7a@1
            - c7a@2
      - template: templates/matrix.yml  # context/controller
        parameters:
          targets:
            - name: RHEL 9.5
              test: rhel/9.5
            - name: FreeBSD 13.4
              test: freebsd/13.4
            - name: FreeBSD 14.2
              test: freebsd/14.2
          groups:
            - c7a@3
            - c7a@4
            - c7a@5
      - template: templates/matrix.yml  # context/controller (ansible-test container management)
        parameters:
          targets:
            - name: Alpine 3.21
              test: alpine/3.21
            - name: Fedora 41
              test: fedora/41
            - name: RHEL 9.5
              test: rhel/9.5
            - name: Ubuntu 24.04
              test: ubuntu/24.04
          groups:
            - c7a@6
  - stage: x86_64
    dependsOn: []
    jobs:
      - template: templates/matrix.yml  # context/target
        parameters:
          targets:
            - name: RHEL 9.5 py39
              test: rhel/9.5@3.9
            - name: RHEL 9.5 py312
              test: rhel/9.5@3.12
            - name: FreeBSD 13.4
              test: freebsd/13.4
            - name: FreeBSD 14.2
              test: freebsd/14.2
          groups:
            - x86_64@1
            - x86_64@2
      - template: templates/matrix.yml  # context/controller
        parameters:
          targets:
            - name: RHEL 9.5
              test: rhel/9.5
            - name: FreeBSD 13.4
              test: freebsd/13.4
            - name: FreeBSD 14.2
              test: freebsd/14.2
          groups:
            - x86_64@3
            - x86_64@4
            - x86_64@5
      - template: templates/matrix.yml  # context/controller (ansible-test container management)
        parameters:
          targets:
            - name: Alpine 3.21
              test: alpine/3.21
            - name: Fedora 41
              test: fedora/41
            - name: RHEL 9.5
              test: rhel/9.5
            - name: Ubuntu 24.04
              test: ubuntu/24.04
          groups:
            - x86_64@6
  - stage: aarch64
    dependsOn: []
    jobs:
      - template: templates/matrix.yml  # context/target
        parameters:
          targets:
            - name: RHEL 9.5 py39
              test: rhel/9.5@3.9
            - name: RHEL 9.5 py312
              test: rhel/9.5@3.12
            - name: FreeBSD 13.4
              test: freebsd/13.4
            - name: FreeBSD 14.2
              test: freebsd/14.2
          groups:
            - aarch64@1
            - aarch64@2
      - template: templates/matrix.yml  # context/controller
        parameters:
          targets:
            - name: RHEL 9.5
              test: rhel/9.5
            - name: FreeBSD 13.4
              test: freebsd/13.4
            - name: FreeBSD 14.2
              test: freebsd/14.2
          groups:
            - aarch64@3
            - aarch64@4
            - aarch64@5
      - template: templates/matrix.yml  # context/controller (ansible-test container management)
        parameters:
          targets:
            - name: Alpine 3.21
              test: alpine/3.21
            - name: Fedora 41
              test: fedora/41
            - name: RHEL 9.5
              test: rhel/9.5
            - name: Ubuntu 24.04
              test: ubuntu/24.04
          groups:
            - aarch64@6
