trigger:
  batch: true
  branches:
    include:
      - devel
      - stable-*

pr:
  autoCancel: true
  branches:
    include:
      - devel
      - stable-*

schedules:
  - cron: 0 7 * * *
    displayName: Nightly
    always: true
    branches:
      include:
        - devel
        - stable-*

variables:
  - name: checkoutPath
    value: ansible
  - name: coverageBranches
    value: devel
  - name: entryPoint
    value: .azure-pipelines/commands/entry-point.sh
  - name: fetchDepth
    value: 500
  - name: defaultContainer
    value: quay.io/ansible/azure-pipelines-test-container:7.0.0

pool: Standard

stages:
  - stage: Sanity
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          nameFormat: Test {0}
          testFormat: sanity/{0}
          targets:
            - test: 1
            - test: 2
  - stage: Units
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          nameFormat: Python {0}
          testFormat: units/{0}
          targets:
            - test: 3.9
            - test: '3.10'
            - test: 3.11
            - test: 3.12
            - test: 3.13
            - test: 3.14
            - test: 3.15
  - stage: Windows
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          nameFormat: Server {0}
          testFormat: windows/{0}/1
          targets:
            - name: 2019 WinRM HTTPS WinPS
              test: 2019/winrm/https/5.1
            - name: 2022 WinRM HTTPS WinPS
              test: 2022/winrm/https/5.1
            - name: 2022 PSRP HTTP WinPS
              test: 2022/psrp/http/5.1
            - name: 2022 SSH Key WinPS
              test: 2022/ssh/key/5.1
            - name: 2025 PSRP HTTP WinPS
              test: 2025/psrp/http/5.1
            - name: 2025 SSH Key WinPS
              test: 2025/ssh/key/5.1
            - name: 2025 WinRM HTTP Pwsh
              test: 2025/winrm/http/7.6
            - name: 2025 PSRP HTTP Pwsh
              test: 2025/psrp/http/7.6
            - name: 2025 SSH Key Pwsh
              test: 2025/ssh/key/7.6
  - stage: Remote
    dependsOn: []
    jobs:
      - template: templates/matrix.yml  # context/target
        parameters:
          targets:
            - name: macOS 26.3
              test: macos/26.3
            - name: RHEL 9.7 py39
              test: rhel/9.7@3.9
            - name: RHEL 9.7 py312
              test: rhel/9.7@3.12
            - name: RHEL 10.1
              test: rhel/10.1
            - name: FreeBSD 14.4
              test: freebsd/14.4
            - name: FreeBSD 15.0
              test: freebsd/15.0
          groups:
            - 1
            - 2
      - template: templates/matrix.yml  # context/controller
        parameters:
          targets:
            - name: macOS 26.3
              test: macos/26.3
            - name: RHEL 9.7
              test: rhel/9.7
            - name: RHEL 10.1
              test: rhel/10.1
            - name: FreeBSD 14.4
              test: freebsd/14.4
            - name: FreeBSD 15.0
              test: freebsd/15.0
          groups:
            - 3
            - 4
            - 5
      - template: templates/matrix.yml  # context/controller (ansible-test container management)
        parameters:
          targets:
            - name: Alpine 3.23
              test: alpine/3.23
            - name: Fedora 44
              test: fedora/44
            - name: RHEL 9.7
              test: rhel/9.7
            - name: RHEL 10.1
              test: rhel/10.1
            - name: Ubuntu 24.04
              test: ubuntu/24.04
          groups:
            - 6
  - stage: Remote_Targeted
    displayName: Remote Targeted
    dependsOn: []
    jobs:
      - template: templates/matrix.yml  # targeted tests
        parameters:
          testFormat: "{0}/targeted"
          targets:
            - name: RHEL 8.10
              test: rhel/8.10/rhel8
  - stage: Docker
    dependsOn: []
    jobs:
      - template: templates/matrix.yml  # context/target
        parameters:
          testFormat: linux/{0}
          targets:
            - name: Alpine 3.23
              test: alpine323
            - name: Fedora 44
              test: fedora44
            - name: Ubuntu 22.04
              test: ubuntu2204
            - name: Ubuntu 24.04
              test: ubuntu2404
          groups:
            - 1
            - 2
      - template: templates/matrix.yml  # context/controller
        parameters:
          testFormat: linux/{0}
          targets:
            - name: Alpine 3.23
              test: alpine323
            - name: Fedora 44
              test: fedora44
            - name: Ubuntu 24.04
              test: ubuntu2404
          groups:
            - 3
            - 4
            - 5
      - template: templates/matrix.yml  # context/target (dnf-oldest, dnf-latest)
        parameters:
          testFormat: linux/{0}
          targets:
            - name: Fedora 44
              test: fedora44
          groups:
            - 7
  - stage: PowerShell
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          nameFormat: PowerShell {0}
          testFormat: powershell/{0}/1
          targets:
            - name: 7.6
  - stage: Galaxy
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          nameFormat: Python {0}
          testFormat: galaxy/{0}/1
          targets:
            - test: 3.12
            - test: 3.13
            - test: 3.14
            - test: 3.15
  - stage: Generic
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          nameFormat: Python {0}
          testFormat: generic/{0}/1
          targets:
            - test: 3.12
            - test: 3.13
            - test: 3.14
            - test: 3.15
  - stage: Incidental_Windows
    displayName: Incidental Windows
    dependsOn: []
    jobs:
      - template: templates/matrix.yml
        parameters:
          nameFormat: Server {0}
          testFormat: i/windows/{0}
          targets:
            - name: 2019 WinRM HTTPS WinPS
              test: 2019/winrm/https/5.1
            - name: 2022 WinRM HTTPS WinPS
              test: 2022/winrm/https/5.1
            - name: 2022 PSRP HTTP WinPS
              test: 2022/psrp/http/5.1
            - name: 2022 SSH Key WinPS
              test: 2022/ssh/key/5.1
            - name: 2025 PSRP HTTP WinPS
              test: 2025/psrp/http/5.1
            - name: 2025 SSH Key WinPS
              test: 2025/ssh/key/5.1
            - name: 2025 WinRM HTTP Pwsh
              test: 2025/winrm/http/7.6
            - name: 2025 PSRP HTTP Pwsh
              test: 2025/psrp/http/7.6
            - name: 2025 SSH Key Pwsh
              test: 2025/ssh/key/7.6
  - stage: Summary
    condition: succeededOrFailed()
    dependsOn:
      - Sanity
      - Units
      - Windows
      - Remote
      - Remote_Targeted
      - Docker
      - PowerShell
      - Galaxy
      - Generic
      - Incidental_Windows
    jobs:
      - template: templates/coverage.yml
